### ISSUE TITLE
bug: UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by joseajohnson** [ryanmurakami/hbfl#31]
As mentioned in the Discus conversation:

On build from AWS `t2.micro` instance, the error below occurs, related to webpack and `source-map`-> `CssMinimizerPlugin`.

The same code will execute locally without a problem, but is a show stopper when deployed.

Updating to the latest version seems to fix the single cpu issue.

```js 
// file:package.json
// from
    "css-minimizer-webpack-plugin": "1.1.5",
// to
    "css-minimizer-webpack-plugin": "1.2.0",
```

A similar error was reproduced and reported here:

https://github.com/webpack-contrib/css-minimizer-webpack-plugin/issues/51

https://github.com/webpack-contrib/css-minimizer-webpack-plugin/releases/tag/v1.2.0

```
[   96.538557] cloud-init[3228]: (node:3407) UnhandledPromiseRejectionWarning: Error: "version" is a required argument.
[   96.550866] cloud-init[3228]: at Object.getArg (/hbfl/node_modules/webpack/node_modules/source-map/lib/util.js:24:11)
[   96.568571] cloud-init[3228]: at new BasicSourceMapConsumer (/hbfl/node_modules/webpack/node_modules/source-map/lib/source-map-consumer.js:294:22)
[   96.588599] cloud-init[3228]: at new SourceMapConsumer (/hbfl/node_modules/webpack/node_modules/source-map/lib/source-map-consumer.js:22:7)
[   96.604706] cloud-init[3228]: at SourceMapSource.node (/hbfl/node_modules/webpack/node_modules/webpack-sources/lib/SourceMapSource.js:193:4)
[   96.611777] cloud-init[3228]: at exports.getSourceAndMap (/hbfl/node_modules/webpack/node_modules/webpack-sources/lib/helpers.js:20:27)
[   96.624458] cloud-init[3228]: at SourceMapSource.sourceAndMap (/hbfl/node_modules/webpack/node_modules/webpack-sources/lib/SourceMapSource.js:184:10)
[   96.640602] cloud-init[3228]: at getTaskForFile (/hbfl/node_modules/webpack/lib/SourceMapDevToolPlugin.js:78:30)
[   96.651391] cloud-init[3228]: at /hbfl/node_modules/webpack/lib/SourceMapDevToolPlugin.js:266:22
[   96.669602] cloud-init[3228]: at /hbfl/node_modules/webpack/lib/Cache.js:93:5
[   96.675707] cloud-init[3228]: at Hook.eval [as callAsync] (eval at create (/hbfl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
[   96.684609] cloud-init[3228]: (node:3407) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by ryanmurakami** [comment]
Hi @joseajohnson, Thanks so much for reporting this! I've updated the project to fix it.
