### ISSUE TITLE
KeyName is not defined error 

### ISSUE THREAD

**Issue by zerozerocoo** [ryanmurakami/hbfl#9]
Hi Ryan, I am running into this error when running this command:
node create-ec2-instance.js
this is at creating an ec2 instance video.

`Failed to create instance with: ReferenceError: KeyName is not defined
    at createKeyPair (/Users/noahchan/aws_learn/hbfl/scripts/module_02/create-ec2-instance.js:74:18)
    at createSecurityGroup.then (/Users/noahchan/aws_learn/hbfl/scripts/module_02/create-ec2-instance.js:15:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)`

I checked through my code and there is a 
const keyName = 'hamster_key'
what else is it asking for?

**Comment by zerozerocoo** [comment]
I got this problem resolved. Missing Param.
